---
name: "jellyfin-plugin-airtimes"
guid: "27b03c3b-9e2a-4f47-941a-82bbb5beedd8"
category: "Metadata"
overview: "Localised series air times from TheTVDB"
description: >
  Localise the series air times provided by TheTVDB to your servers timezone.
  Must be above the original TheTVDB plugin in the metadata sources list.
owner: "apteryxxyz"

version: "0.0.1.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
artifacts:
- "Jellyfin.Plugin.AirTimes.dll"
